# Generated by Django 2.2 on 2019-12-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191225_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': '注册成员', 'verbose_name_plural': '注册成员'},
        ),
    ]
