# Generated by Django 2.2 on 2019-12-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191226_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': '邮件确认码', 'verbose_name_plural': '邮件确认码'},
        ),
    ]
