# Generated by Django 2.2.8 on 2019-12-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191227_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='confirmstring',
            name='code',
            field=models.CharField(max_length=256, verbose_name='确认码'),
        ),
    ]
